services:
  groupme-bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "18080:18080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
